### ISSUE TITLE
hi, some thing about  https://golang.org/src/database/sql/sql.go#L1045

### ISSUE THREAD

**Issue by domac** [wmin0/web3-extends#1]
I would like to ask if the repair of this code works normally and can reduce the establishment of close_wait stuck?

https://golang.org/src/database/sql/sql.go#L1045

您好,冒昧问下.我想问下您这次对这个修改, 在实际的场景中确实可以正常关闭socket,并能解决到close_wait的问题吗?谢谢

**Comment by domac** [comment]
I would like to ask if the repair of this code works normally and can reduce the establishment of close_wait stuck?

https://github.com/lib/pq/pull/722

您好,冒昧问下.我想问下您这次对这个修改, 在实际的场景中确实可以正常关闭socket,并能解决到close_wait的问题吗?谢谢

**Comment by wmin0** [comment]
not relevant to this repo
